-- Views for requested reports
SET search_path = public;

-- 1) List each person with total billed, including zero
CREATE OR REPLACE VIEW v_persona_total AS
SELECT 
  p.per_id,
  p.per_nombre,
  p.per_apellido,
  COALESCE(SUM(fd.line_total), 0)::NUMERIC(18,2) AS total_facturado
FROM persona p
LEFT JOIN fact_encabezado fe ON fe.zper_id = p.per_id
LEFT JOIN fact_detalle   fd ON fd.zfenc_id = fe.fenc_id
GROUP BY p.per_id, p.per_nombre, p.per_apellido;

-- 2) Person(s) who bought the most expensive product
CREATE OR REPLACE VIEW v_persona_producto_mas_caro AS
WITH max_price AS (
  SELECT MAX(prod_precio) AS maxp FROM producto
)
SELECT DISTINCT
  p.per_id,
  p.per_nombre,
  p.per_apellido,
  pr.prod_id,
  pr.prod_descripcion,
  pr.prod_precio
FROM persona p
JOIN fact_encabezado fe ON fe.zper_id = p.per_id
JOIN fact_detalle   fd ON fd.zfenc_id = fe.fenc_id
JOIN producto       pr ON pr.prod_id = fd.zprod_id
JOIN max_price      mp ON pr.prod_precio = mp.maxp;

-- 3) Products by total quantity billed (use ORDER BY in consumer query)
CREATE OR REPLACE VIEW v_productos_por_cantidad AS
SELECT 
  pr.prod_id,
  pr.prod_descripcion,
  COALESCE(SUM(fd.fdet_cantidad), 0)::NUMERIC(18,2) AS cantidad_facturada
FROM producto pr
LEFT JOIN fact_detalle fd ON fd.zprod_id = pr.prod_id
GROUP BY pr.prod_id, pr.prod_descripcion;

-- 4) Products by profit (utilidad) generated by billing
-- utilidad = SUM((unit_price - prod_costo) * cantidad)
CREATE OR REPLACE VIEW v_productos_por_utilidad AS
SELECT 
  pr.prod_id,
  pr.prod_descripcion,
  COALESCE(SUM((fd.unit_price - pr.prod_costo) * fd.fdet_cantidad), 0)::NUMERIC(18,2) AS utilidad_total
FROM producto pr
LEFT JOIN fact_detalle fd ON fd.zprod_id = pr.prod_id
GROUP BY pr.prod_id, pr.prod_descripcion;

-- 5) Products and margin of profit per product according to billing
-- ingresos = SUM(line_total)
-- utilidad = SUM((unit_price - prod_costo) * cantidad)
-- margen = utilidad / ingresos
CREATE OR REPLACE VIEW v_productos_margen AS
WITH base AS (
  SELECT 
    pr.prod_id,
    pr.prod_descripcion,
    COALESCE(SUM(fd.line_total), 0)::NUMERIC(18,2) AS ingresos,
    COALESCE(SUM((fd.unit_price - pr.prod_costo) * fd.fdet_cantidad), 0)::NUMERIC(18,2) AS utilidad
  FROM producto pr
  LEFT JOIN fact_detalle fd ON fd.zprod_id = pr.prod_id
  GROUP BY pr.prod_id, pr.prod_descripcion
)
SELECT 
  prod_id,
  prod_descripcion,
  ingresos,
  utilidad,
  CASE WHEN NULLIF(ingresos, 0) IS NULL THEN NULL
       ELSE ROUND(utilidad / NULLIF(ingresos, 0), 4)
  END AS margen
FROM base;
